/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMirrorWriteRaceOracleInterface extends ethers.utils.Interface {
  functions: {
    "updateRoot(bytes32)": FunctionFragment;
    "verify(address,uint256,bytes32[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "updateRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [string, BigNumberish, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "updateRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "UpdatedRoot(bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdatedRoot"): EventFragment;
}

export class IMirrorWriteRaceOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMirrorWriteRaceOracleInterface;

  functions: {
    updateRoot(
      newRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateRoot(bytes32)"(
      newRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    verify(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verify(address,uint256,bytes32[])"(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  updateRoot(
    newRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateRoot(bytes32)"(
    newRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  verify(
    account: string,
    index: BigNumberish,
    proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verify(address,uint256,bytes32[])"(
    account: string,
    index: BigNumberish,
    proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    updateRoot(newRoot: BytesLike, overrides?: CallOverrides): Promise<void>;

    "updateRoot(bytes32)"(
      newRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    verify(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verify(address,uint256,bytes32[])"(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    UpdatedRoot(oldRoot: null, newRoot: null): EventFilter;
  };

  estimateGas: {
    updateRoot(newRoot: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "updateRoot(bytes32)"(
      newRoot: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    verify(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(address,uint256,bytes32[])"(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    updateRoot(
      newRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateRoot(bytes32)"(
      newRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    verify(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(address,uint256,bytes32[])"(
      account: string,
      index: BigNumberish,
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
